# @format

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: release-please-action
          extra-files:
            - type: json
              path: ./package.json
              jsonpath: $.version
            - type: json
              path: ./packages/chrome/package.json
              jsonpath: $.version
            - type: json
              path: ./packages/common/package.json
              jsonpath: $.version
            - type: json
              path: ./packages/electron/package.json
              jsonpath: $.version
            - type: json
              path: ./packages/common/src/meta.json
              jsonpath: $.version
